[package]
name = "battle-io"
version = "0.1.0"
edition = "2021"

[dependencies]
gstd = { version = "1", features = ["debug"] }
parity-scale-codec = { version = "3", default-features = false }
gmeta = { version = "1" }
scale-info = { version = "2", default-features = false, features = ["derive"] }
